### ISSUE TITLE
Capping raspivid fps at 120 is too conservative for v2 camera

### ISSUE THREAD

**Issue by Hermann-SW** [6by9/userland#13]
See several videos taken with raspivid at 180fps (with the help of I2C commands injected later), starting here:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=204775#p1275741

Please increase cap value to 180 at least, that will allow everybody with standard raspivid to take 640x480 videos at 180fps (and not only at 120fps, or 90fps as documented).

![180fps.train1.png](https://stamm-wilbrandt.de/en/forum/180fps.train1.png)

**Comment by 6by9** [comment]
Already done - https://github.com/Hexxeh/rpi-firmware/commit/f6f7e04d01f95b86633c1722a179a5fce426c24e

> firmware: imx219: Increase max frame rate at 640x480 to 200fps
