### ISSUE TITLE
raspivid locks up above 202 fps for unclear reasons

### ISSUE THREAD

**Issue by Hermann-SW** [6by9/userland#14]
You state that in this posting:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=204775#p1270144

This is major blocker of bringing over raspiraw high framerate features from raspiraw (v2 camera can do easily 640x480 at 240fps with raspiraw, and even 640x215 at 420fps with very few frame skips; v1 camera can do 640x64 at 665fps with raspiraw without frameskips).

I would expect raspivid to show >500fps with v1 camera at least if this blocker issue will be fixed.

**Comment by 6by9** [comment]
This is only my fork of the main raspberrypi/userland repo, mainly used for creating PRs. Unless it is on a forked branch, any issue should be raised in the upstream repo.

But also there has never been any promise of any increase in the frame rate. The main camera stack is synchronous between tuner control algorithms and processing, and there is no easy way to reduce the time the tuner takes on each frame, therefore there is a hard limit on the max frame rate.
The simple answer is that if you want these very high frame rate modes then you have to use raspiraw and do your own manual AE and AWB control.
