### ISSUE TITLE
probe_sensor in raspiraw.c is leaking

### ISSUE THREAD

**Issue by QiangLi1016** [6by9/userland#6]
If the while loop does not find any sensor, the function still return the last sensor searched, instead of NULL.

**Comment by 6by9** [comment]
Not really a leak as there is no allocation involved.

It is true that it does return the last sensor.
(a) it is really only test code. Error handling is pretty minimal.
(b) I'm actually making use of that at the moment whilst developing something else!
(c) it could really do with more sensible command line parsing, and that should allow specifying the sensor and also the use of I2C_FORCE_SLAVE to ignore kernel drivers that have registered the I2C port/address combination.

**Comment by 6by9** [comment]
Fixed.
